openfoam: auto updated to 13.20250706+65eda17-2

diff --git a/x86_64/openfoam/PKGBUILD b/x86_64/openfoam/PKGBUILD
--- a/x86_64/openfoam/PKGBUILD
+++ b/x86_64/openfoam/PKGBUILD
@@ -7,110 +7,152 @@
 
 pkgbase=openfoam
 pkgname=openfoam-org
-pkgver=12.20250206
-_pkgver="${pkgver%.*}"
-_subver="${pkgver#*.}"
-[[ "$pkgver" = "$_subver" ]] && _subver="version-$pkgver"
-pkgrel=5
+pkgver=13.20250706+65eda17
+_pkgver="${pkgver%%.*}"
+_subver_and_commit="${pkgver#*.}"
+_subver="${_subver_and_commit%+*}"
+_commit="${pkgver#*+}"
+pkgrel=2
 pkgdesc="The open source CFD toolbox (www.openfoam.org)"
 _distpkgbase=OpenFOAM
 _gitname=$_distpkgbase-$_pkgver
+options=(!strip)
 arch=('x86_64')
 url="http://www.openfoam.org"
 license=("GPL-3.0-or-later")
 depends=(
-  'bzip2'
-  'paraview'
-  'parmetis-git' #git until parmetis is fixed
-  'scotch'
-  'boost'
-  'flex'
-  'cgal'
-  'zoltan' # provided separately from 'trilinos'
+  glibc
+  qt6-base
+  gcc-libs
+  metis
+  vtk
+  bzip2
+  paraview
+  parmetis
+  scotch
+  boost
+  cgal
+  zoltan
+  openmpi
+  gnuplot
+  libxt
+  libxml2
+  freetype2
+  double-conversion
+  glew
+  utf8cpp
+  gl2ps
+  python
+  hdf5
+  zlib
 )
-makedepends=('bash')
-provides=('openfoam')
-source=("${pkgname}-${pkgver}.tar.gz::https://github.com/OpenFOAM/$_gitname/archive/refs/tags/$_subver.tar.gz")
+makedepends=(
+  git
+  cmake
+  cli11 
+  nlohmann-json 
+  fast_float 
+  flex
+)
+provides=(openfoam)
+source=(
+  "$_gitname-$_subver::git+https://github.com/OpenFOAM/OpenFOAM-${_pkgver}.git#commit=${_commit}"
+  paraview.arch
+  openfoam.install
+)
 install="${pkgbase}.install"
-md5sums=('3907dd4f5e2c5cb793ecf5666f89b917')
+sha256sums=('0819222f24fa6395181684058ccb2397579fdb015b60ae3a9cc992757f4c79db'
+            'bbec057b1153a616ea388dc80fdaeb6337edc6150e0601f140a1304f82a10ddb'
+            'a94080d4e5bc4736868269d66f61f5430dec961c70bdcdaa1c9a402dba5203d2')
+
+_cache_notify() {
+  local yellow='\033[1;33m'
+  local red='\033[1;31m'
+  local nc='\033[0m'
+  echo -e "${yellow}==> Using build cache:${nc}"
+  echo "    ${srcdir}/${_distpkgbase}-${_pkgver}"
+  echo
+  echo -e "${yellow}==> To build from scratch, run:${nc}"
+  echo -e "    ${red}rm -rf ${srcdir}/${_distpkgbase}-${_pkgver}${nc}"
+}
 
 prepare() {
-  if [ ! -d $srcdir/$_distpkgbase-$_pkgver ]; then
-    mv $srcdir/$_gitname-$_subver $srcdir/$_distpkgbase-$_pkgver
-    # Extract the current version and major of paraview and of scotch for use in the system preferences
-    #_pversion=`pacman -Q paraview | sed -e 's/.* //; s/-.*//g'`
-    _pversion=$(pacman -Q $(pacman -Qqo $(which paraview)) | sed -e 's/.* //; s/-.*//g')
-    _pmajor=$(echo $_pversion | cut -d '.' -f1)
-    _sversion=$(pacman -Q scotch | sed -e 's/.* //; s/-.*//g')
+  _cachefile=${_distpkgbase}-${_pkgver}/.arch_cache
+  if [[ -f "$_cachefile" ]] && grep -q "$pkgver" "$_cachefile"; then
+    _cache_notify
+  else
+    rm -rf $_distpkgbase-$_pkgver
+    mv $_gitname-$_subver $_distpkgbase-$_pkgver
 
-    # Generate and install the system preferences file
-    echo "compilerInstall=system" >${srcdir}/prefs.sh
-    echo "export WM_MPLIB=SYSTEMOPENMPI" >>${srcdir}/prefs.sh
-    echo "export ParaView_VERSION=${_pversion}" >>${srcdir}/prefs.sh
-    echo "export ParaView_MAJOR=${_pmajor}" >>${srcdir}/prefs.sh
-    cp ${srcdir}/prefs.sh ${srcdir}/${_distpkgbase}-${_pkgver}/etc
+    _bashrc=${_distpkgbase}-${_pkgver}/etc/bashrc
+    sed -i "s|^export WM_PROJECT_VERSION=.*|export WM_PROJECT_VERSION=${_pkgver}|" "$_bashrc"
+    cp ${_bashrc} ${_bashrc}.prepared
 
-    # Generate the scotch.sh file for arch
-    echo "export SCOTCH_VERSION=scotch_${_sversion}" >${srcdir}/scotch.sh
-    echo "export SCOTCH_ARCH_PATH=/usr" >>${srcdir}/scotch.sh
-    cp ${srcdir}/scotch.sh ${srcdir}/${_distpkgbase}-${_pkgver}/etc/config
+    # we'll be using $bashrc while building, and replace it with $bashrc.prepared
+    # (below) during install - so we have to modify the FOAM_INST_DIR for post-install use
+    sed -i 's|^# export FOAM_INST_DIR=.*|export FOAM_INST_DIR=/opt/\$WM_PROJECT|' \
+      ${_bashrc}.prepared
 
-    sed -i 's/export SCOTCH_TYPE=.*/export SCOTCH_TYPE=system/' ${srcdir}/${_distpkgbase}-${_pkgver}/etc/bashrc
-    sed -i 's/export METIS_TYPE=.*/export METIS_TYPE=system/' ${srcdir}/${_distpkgbase}-${_pkgver}/etc/bashrc
-    sed -i 's/export PARMETIS_TYPE=.*/export PARMETIS_TYPE=system/' ${srcdir}/${_distpkgbase}-${_pkgver}/etc/bashrc
-    sed -i 's/export ZOLTAN_TYPE=.*/export ZOLTAN_TYPE=system/' ${srcdir}/${_distpkgbase}-${_pkgver}/etc/bashrc
-    cp ${srcdir}/${_distpkgbase}-${_pkgver}/etc/bashrc ${srcdir}/${_distpkgbase}-${_pkgver}/etc/bashrc.prepared
-    sed -i 's|^# export FOAM_INST_DIR=.*|export FOAM_INST_DIR=/opt/\$WM_PROJECT|' ${srcdir}/${_distpkgbase}-${_pkgver}/etc/bashrc.prepared
-    #
-    # The following (2) lines are to fix https://bugs.openfoam.org/view.php?id=4126
-    sed -i 's|libpqCore-pv|libpqCore|' ${srcdir}/${_distpkgbase}-${_pkgver}/etc/config.sh/paraview
-    sed -i 's|xargs dirname|xargs dirname \| xargs realpath|' ${srcdir}/${_distpkgbase}-${_pkgver}/etc/config.sh/paraview
+    # Add system library settings to prefs.sh
+    cat <<EOF >"${_distpkgbase}-${_pkgver}/etc/prefs.sh"
+# System-wide settings for Arch Linux
+export SCOTCH_TYPE=system
+export METIS_TYPE=system
+export PARMETIS_TYPE=system
+export ZOLTAN_TYPE=system
+EOF
+
+    echo $pkgver >$_cachefile
   fi
+
+  # Drop in Arch paraview environment script
+  cd ${_distpkgbase}-${_pkgver}
+  cp ${srcdir}/paraview.arch etc/config.sh/paraview
 }
 
 build() {
+  cd ${_distpkgbase}-${_pkgver}
+  # export FOAM_VERBOSE=1
+  # export PS1='~' # required for verbosity checks
   # Setup the build environment
-  export FOAM_INST_DIR=${srcdir}
-  foamDotFile=${srcdir}/${_distpkgbase}-${_pkgver}/etc/bashrc
-  [ -f ${foamDotFile} ] || return 1
+  source etc/bashrc || true
 
-  # Enter build directory
-  cd ${srcdir}/${_distpkgbase}-${_pkgver}
-
-  # Build and clean up OpenFOAM
-  bash -c """
-  export PATH="/opt/paraview/bin:\$PATH"
-  source ${foamDotFile}
-  ./Allwmake
-  wclean all
+  # see if we have extra threads available in /etc/makepkg.conf MAKEFLAGS
+  [[ $MAKEFLAGS =~ -j[[:space:]]*([0-9]+) ]] &&
+    _jval="${BASH_REMATCH[1]}" || _jval=1
+  
+  export PATH="$PWD/wmake:$PATH" 
   wmakeLnIncludeAll
-  """
+  ./Allwmake -s -q -j ${_jval:=1}
 }
 
 package() {
-  cd ${srcdir}
-
   # Create destination directories
   install -d "${pkgdir}/opt/${_distpkgbase}" "${pkgdir}/etc/profile.d"
 
   # Copy package to pkgdir
-  cp -r "${srcdir}/${_distpkgbase}-${_pkgver}" "${pkgdir}/opt/${_distpkgbase}"
+  cp -r "${_distpkgbase}-${_pkgver}" "${pkgdir}/opt/${_distpkgbase}"
 
-  # Add source file
-  echo "export FOAM_INST_DIR=/opt/${_distpkgbase}" >${pkgdir}/etc/profile.d/openfoam-${_pkgver}.sh
-  echo "export PATH=/opt/paraview/bin:\$PATH" >>${pkgdir}/etc/profile.d/openfoam-${_pkgver}.sh
-  echo "alias ofoam=\"source \${FOAM_INST_DIR}/${_distpkgbase}-${_pkgver}/etc/bashrc\"" >>${pkgdir}/etc/profile.d/openfoam-${_pkgver}.sh
-  chmod 755 "${pkgdir}/etc/profile.d/openfoam-${_pkgver}.sh"
+  # Clean up build files
+  # https://openfoamwiki.net/index.php/Installation/Delete_intermediate_files#OpenFOAM_v1706_and_newer
+  _baseclean="${pkgdir}/opt/${_distpkgbase}/${_distpkgbase}-${_pkgver}"
+  rm -rf ${_baseclean}/platforms/*/applications ${_baseclean}/platforms/*/src
+
+  # Add bash profile
+  _bash_profile=${pkgdir}/etc/profile.d/openfoam-${_pkgver}.sh
+  echo "export FOAM_INST_DIR=/opt/${_distpkgbase}" >$_bash_profile
+  echo "alias ofoam=\"source \${FOAM_INST_DIR}/${_distpkgbase}-${_pkgver}/etc/bashrc\"" \
+    >>$_bash_profile
+  echo "alias ofoam${_pkgver}=\"source \${FOAM_INST_DIR}/${_distpkgbase}-${_pkgver}/etc/bashrc\"" \
+    >>$_bash_profile
+  chmod 755 $_bash_profile
 
   # Add stub thirdparty directory to keep openfoam happy
   install -d "${pkgdir}/opt/${_distpkgbase}/ThirdParty-${_pkgver}"
 
-  # Permission fixes - for system-wide install and use
-  chmod -R go+r "${pkgdir}/opt"
-  chmod -R 755 "${pkgdir}/opt/${_distpkgbase}/${_distpkgbase}-${_pkgver}/bin"
-  chmod -R 755 "${pkgdir}/opt/${_distpkgbase}/${_distpkgbase}-${_pkgver}/etc"
-  rm "${pkgdir}/opt/${_distpkgbase}/${_distpkgbase}-${_pkgver}/etc/bashrc"
-  install -Dm 755 "${srcdir}/${_distpkgbase}-${_pkgver}/etc/bashrc.prepared" "${pkgdir}/opt/${_distpkgbase}/${_distpkgbase}-${_pkgver}/etc/bashrc"
+  install -Dm755 "${_distpkgbase}-${_pkgver}/etc/bashrc.prepared" \
+    "${pkgdir}/opt/${_distpkgbase}/${_distpkgbase}-${_pkgver}/etc/bashrc"
+  install -Dm644 ${_distpkgbase}-${_pkgver}/COPYING -t $pkgdir/usr/share/licenses/$pkgname
 }
 
 # vim:set ts=2 sw=2 et:
