aomp-amdgpu: auto updated to 11.9.0-1

diff --git a/aomp-amdgpu/remove_gcc_logic.patch b/aomp-amdgpu/remove_gcc_logic.patch
--- a/aomp-amdgpu/remove_gcc_logic.patch
+++ b/aomp-amdgpu/remove_gcc_logic.patch
@@ -1,11 +1,11 @@
-*** aomp/bin/build_openmp.sh.bak	2020-07-11 16:55:42.995876206 +0200
---- aomp/bin/build_openmp.sh	2020-07-11 16:56:14.952367513 +0200
+*** aomp/bin/build_openmp.sh.bak	2020-09-17 17:07:31.393892767 +0200
+--- aomp/bin/build_openmp.sh	2020-09-17 17:08:19.766760059 +0200
 ***************
-*** 73,106 ****
+*** 73,117 ****
      $SUDO rm $INSTALL_OPENMP/testfile
   fi
   
-! GCCMIN=7
+! GCCMIN=8
 ! if [ "$AOMP_BUILD_CUDA" == 1 ] ; then
 !    if [ -f $CUDABIN/nvcc ] ; then
 !       CUDAVER=`$CUDABIN/nvcc --version | grep compilation | cut -d" " -f5 | cut -d"." -f1 `
@@ -16,14 +16,14 @@
 !    fi
 ! fi
 ! 
-! function getgcc7orless(){
+! function getgcc8orless(){
 !    _loc=`which gcc`
 !    [ "$_loc" == "" ] && return
 !    gccver=`$_loc --version | grep gcc | cut -d")" -f2 | cut -d"." -f1`
 !    [ $gccver -gt $GCCMIN ] && _loc=`which gcc-$GCCMIN`
 !    echo $_loc
 ! }
-! function getgxx7orless(){
+! function getgxx8orless(){
 !    _loc=`which g++`
 !    [ "$_loc" == "" ] && return
 !    gxxver=`$_loc --version | grep g++ | cut -d")" -f2 | cut -d"." -f1`
@@ -31,17 +31,28 @@
 !    echo $_loc
 ! }
 ! 
-! GCCLOC=$(getgcc7orless)
-! GXXLOC=$(getgxx7orless)
-  if [ "$GCCLOC" == "" ] ; then
-     echo "ERROR: NO ADEQUATE gcc"
-     echo "       Please install gcc-5 or gcc-7"
+! GCCLOC=$(getgcc8orless)
+! GXXLOC=$(getgxx8orless)
+! if [ "$GCCLOC" == "" ] ; then
+!    echo "ERROR: NO ADEQUATE gcc"
+!    echo "       Please install gcc-5, gcc-7, or gcc-8"
+!    exit 1
+! fi
+! if [ "$GXXLOC" == "" ] ; then
+!    echo "ERROR: NO ADEQUATE g++"
+!    echo "       Please install g++-5, g++-7, or g++-8"
+!    exit 1
+! fi
+! 
+  export LLVM_DIR=$AOMP_INSTALL_DIR
+  GFXSEMICOLONS=`echo $GFXLIST | tr ' ' ';' `
+  COMMON_CMAKE_OPTS="-DOPENMP_ENABLE_LIBOMPTARGET=1
 --- 73,80 ----
      $SUDO rm $INSTALL_OPENMP/testfile
   fi
   
 ! GCCLOC=/usr/bin/gcc
 ! GXXLOC=/usr/bin/g++
-  if [ "$GCCLOC" == "" ] ; then
-     echo "ERROR: NO ADEQUATE gcc"
-     echo "       Please install gcc-5 or gcc-7"
+  export LLVM_DIR=$AOMP_INSTALL_DIR
+  GFXSEMICOLONS=`echo $GFXLIST | tr ' ' ';' `
+  COMMON_CMAKE_OPTS="-DOPENMP_ENABLE_LIBOMPTARGET=1
